schema: src/schemas/schema.graphql
extensions:
  endpoints:
    Default GraphQL Endpoint:
      url: http://127.0.0.1:5001/graphql
      headers:
        user-agent: JS GraphQL
      introspect: true
