version: '3.7'
services:
  postgres:
    image: postgres:14-alpine
    restart: always
    environment:
      - POSTGRES_USER=local-user
      - POSTGRES_PASSWORD=local-password
      - POSTGRES_DB=local-db
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5438:5432'
    volumes:
      - ./ci-job/capmetro/stops.txt:/capmetro/stops.txt
      - ./ci-job/capmetro/routes.txt:/capmetro/routes.txt
      - ./ci-job/capmetro/shapes.txt:/capmetro/shapes.txt
      - ./ci-job/capmetro/trips.txt:/capmetro/trips.txt
      - ./ci-job/capmetro/stop_times.txt:/capmetro/stop_times.txt
      - ./ci-job/capmetro/calendar.txt:/capmetro/calendar.txt
      - ./ci-job/capmetro/calendar_dates.txt:/capmetro/calendar_dates.txt
      # copy the sql script to create tables
      - ./server/schema.sql:/docker-entrypoint-initdb.d/create_tables.sql