services:
  # A web service
  - type: web
    name: austin-bus-go
    env: python
    repo: https://github.com/gges5110/austinbusgo.git # optional
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn 'server.app:create_app()'
    branch: main # optional (defaults to master)
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: AustinBusGo
          property: connectionString
  # A static site
  - type: web
    name: austin-bus-go-client
    env: static
    buildCommand: npm run build
    staticPublishPath: ./build
    repo: https://github.com/gges5110/austinbusgo.git # optional
    pullRequestPreviewsEnabled: true # optional
    rootDir: client
    branch: main # optional (defaults to master)
    buildFilter:
      paths:
      - src/**/*.tsx
      ignoredPaths:
      - src/**/*.test.tsx


databases:
  - name: AustinBusGo