name: austinbusgo

services:
  postgres:
    image: postgis/postgis:14-3.3
    restart: always
    environment:
      - POSTGRES_USER=local-user
      - POSTGRES_PASSWORD=local-password
      - POSTGRES_DB=local-db
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5438:5432'
    volumes:
      - ../etl/capmetro:/capmetro
      - ../etl/schema.sql:/docker-entrypoint-initdb.d/create_tables.sql
