# GitHub Actions Workflow for Continuous Deployment

name: Main

# Triggers the workflow on pushes to the 'main' branch
on:
  push:
    branches:
      - main

jobs:
  deploy-client:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"
          cache-dependency-path: client/package-lock.json

      - name: Install Dependencies
        working-directory: ./client
        run: npm ci

      - name: Build Client
        working-directory: ./client
        env:
          VITE_MAPBOX_ACCESS_TOKEN: ${{ secrets.VITE_MAPBOX_ACCESS_TOKEN }}
          VITE_API_BASE: ${{ secrets.VITE_API_BASE }}
          VITE_GTFS_RT_PROXY_URL: ${{ secrets.VITE_GTFS_RT_PROXY_URL }}
        run: npm run build

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./client/build

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  deploy-server:
    permissions:
      contents: read
      id-token: write
    uses: ./.github/workflows/deployBackend.yml
    secrets: inherit
